name: ProkRzd_TicketSystem

services:

  mariadb:
    container_name: mariadb
    env_file:
      - path: ./environment/.secrets.env
        required: true
    build: db/
    volumes:
      - db-data:/var/lib/mysql
    networks:
      osTicketIntraNet:
        ipv4_address: 10.0.0.10
    restart: unless-stopped

  osticket:
    container_name: osTicket
    env_file:
      - path: ./environment/.etc.env
        required: true
    build: php/
    volumes:
      - osticket-data:/var/www/osTicket-1.18.4
      - media-data:/var/lib/osTicketMedia
      - ./tls-certs:/etc/tls-certs
    networks:
      osTicketNet:
      osTicketIntraNet:
        ipv4_address: 10.0.0.5
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_started

networks:
  osTicketNet:
    driver: bridge
  osTicketIntraNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
    internal: true

volumes:
  osticket-data:
    name: "osticket-disk"
  db-data:
    name: "mariadb-disk"
  media-data:
    name: "media-disk"